sudo: required
services:
  - docker

before_install:
  - docker build -t lexworks/docker-react -f Dockerfile.dev .

script:
  - docker run lexworks/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "bdotest"
  env: "Bdotest-env-2"
  bucket_name: "elasticbeanstalk-ap-southeast-1-216847732374"
  bucket_path: "bdotest"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

